a =input('digite algo:')
print('o tipo primitivo desse valor é ',type(a))
print('Só tem espaços ?', a.isspace())
print('É um numero ?',a.isnumeric())
print('É alfabetico?',a.isalpha())
print('é alfanumerico ?',a.isalnum())
print('Está em maiúsculas ?',a.isupper())
print('Está em minúsculas ?',a.islower())
print('Está capitalizada?',a.istitle())